# © 2022,2023 TNG Technology Consulting
#
# SPDX-License-Identifier: Apache-2.0

name: Build and publish PDF artifact

on:
  push:
    tags:
      - 'release/v*'

jobs:
  publish_pdf:
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Build PDF 
        run: ./utils/build_pdf.sh

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "tex/*.pdf,tex/*.jpg"
